<?php

$jsonData = array(
	array(
		'title'   => 'The perfect pair', // The title of Slider item
		'desc'    => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', // The short description of Slider item
		'thumb'   => 'https://images.unsplash.com/32/6Icr9fARMmTjTHqTzK8z_DSC_0123.jpg', // The image url of Slider item
		'classes' => 'slider-item--a', // CSS class for Slider item

        // CTA of Slider item
		'btns'    => array( 'title'   => 'Shop now',
		                    'link'    => '/',
		                    'classes' => 'action primary'
		),
	),

    array(
        'title'   => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', // The title of Slider item
        'desc'    => 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', // The short description of Slider item
        'thumb'   => 'https://images.unsplash.com/photo-1456418047667-56bcd35b1a88?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2550&q=80', // The image url of Slider item
        'classes' => 'slider-item--b', // CSS class for Slider item

        // CTA of Slider item
        'btns'    => array( 'title'   => 'Shop now',
            'link'    => '/',
            'classes' => 'action primary'
        ),
    ),

    array(
        'title'   => 'Quisque at ultrices ex. In et tristique magna, et rhoncus arcu', // The title of Slider item
        'desc'    => 'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur', // The short description of Slider item
        'thumb'   => 'https://images.unsplash.com/photo-1468071174046-657d9d351a40?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1266&q=80', // The image url of Slider item
        'classes' => 'slider-item--c', // CSS class for Slider item

        // CTA of Slider item
        'btns'    => array( 'title'   => 'Shop now',
            'link'    => '/',
            'classes' => 'action primary'
        ),
    ),
);
?>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "vslider_component": {
                    "component": "Van_Slider/js/vslider",
                    "items": <?php echo json_encode( $jsonData ); ?>
                }
            }
        }
    }
}
</script>

<div data-bind="scope: 'vslider_component';">
    <span data-bind="afterRender: initVslider"></span>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>


<script>
    function initVslider(){
        require(["jquery", "vsliderjquery"],function($) {
            $('#vslider').vslider(true, 3000);
        });
    }
</script>
